### PR TITLE
Immediate location search

### LINKED ISSUE #2955: "Advanced" incorrectly highlighted when address search active
The picture below shows mobile, but this is a problem for desktop as well.

When you search for a location, "ADVANCED" is shown in bold with a dot next to it, suggesting that there are hidden search terms. But all search terms are visible.

image

### PR DESCRIPTION
**Pull request by RickMohr**
* Search immediately when choosing a location or species autocomplete option
* When no location search is in effect
  * The "Search by Location" input box contains either a "pencil" icon (if the box is empty) or an "X" (if the box is non-empty).
  * Clicking the "X" clears the box.
* After a successful location search (for an address or named boundary):
  * The (autocompleted) location text is shown in the "Search by Location" area (with styling used for "CUSTOM AREA"), along with an "X"
  * Clicking the "X" clears the box and performs a search with no location filter.

Also:
* Fix #2955 in `updateActiveSearchIndicators` by defining `simpleSearchKeys` before it is used

Testing - here's [my test matrix](https://docs.google.com/a/azavea.com/spreadsheets/d/1GraUliwgF8WSb0g2LNDKl1lcarR6oj_F_49hhcMAFaU)

Connects #3005
Connects #2955

### CODE REVIEW

File: opentreemap/treemap/js/src/lib/searchBar.js [hunk 1]
```diff
@@ -85,32 +88,53 @@ function redirectToSearchPage(filters, wmCoords) {
...
+            reverse: "id",
+            sortKeys: ['sortOrder', 'value'],
+            geocoder: true,
+            geocoderBbox: config.instance.extent
+        }),
+        clearLocationInputStream = $(dom.clearLocationInput).asEventStream('click'),
+        clearLocationSearchStream = $(dom.clearLocationSearch).asEventStream('click'),
+        triggerSearchStream = Bacon.mergeAll(
+            speciesTypeahead.selectStream,
+            locationTypeahead.selectStream.log('yo'),
```
Comment (maurizi) [inline opentreemap/treemap/js/src/lib/searchBar.js]: Looks like a `.log()` statement snuck in here.
